services:
  - type: web
    name: shoka6-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python shoka_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    pythonVersion: 3.10